# Generated by Django 5.0.6 on 2024-06-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='middle_name',
            new_name='middlename',
        ),
    ]
