# Generated by Django 5.0.6 on 2024-06-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_first_name_item_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
