# Generated by Django 5.0.6 on 2024-07-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employee_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Item',
        ),
    ]
