# Generated by Django 5.0.6 on 2024-07-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_permanent_brgy_item_father_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='telephone',
        ),
        migrations.AddField(
            model_name='item',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
